# Generated by Django 2.0.7 on 2018-08-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admnistrator'),
        ),
    ]
